# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 15:06
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_data', '0011_enterpriseuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseenrollment',
            name='enrolled_enterprise_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='enterprise_data.EnterpriseUser'),
        ),
    ]
