# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_data', '0012_enterpriseenrollment_enrolled_enterprise_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterpriseuser',
            options={'ordering': ['-user_email'], 'verbose_name': 'Enterprise User', 'verbose_name_plural': 'Enterprise Users'},
        ),
    ]
