# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_data', '0013_auto_20180831_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterpriseuser',
            options={'ordering': ['-user_email'], 'verbose_name': 'Enterprise User', 'verbose_name_plural': 'Enterprise Users'},
        ),
    ]
