# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_data', '0016_auto_20180924_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseenrollment',
            name='unenrollment_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
