# Generated by Django 2.2.17 on 2021-05-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_data', '0022_remove_role_based_access_control_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseLearner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_user_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('enterprise_customer_uuid', models.UUIDField(db_index=True)),
                ('enterprise_user_created', models.DateTimeField(null=True)),
                ('enterprise_user_modified', models.DateTimeField(null=True)),
                ('enterprise_user_active', models.BooleanField(default=False)),
                ('lms_user_id', models.PositiveIntegerField()),
                ('is_linked', models.BooleanField(default=False)),
                ('user_username', models.CharField(max_length=255, null=True)),
                ('user_email', models.CharField(db_index=True, max_length=255, null=True)),
                ('lms_user_created', models.DateTimeField(null=True)),
                ('lms_last_login', models.DateTimeField(null=True)),
                ('lms_user_country', models.CharField(max_length=2, null=True)),
                ('enterprise_sso_uid', models.CharField(max_length=255, null=True)),
                ('last_activity_date', models.DateField(db_index=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Enterprise Learner',
                'verbose_name_plural': 'Enterprise Learner',
                'db_table': 'ent_base_enterprise_user',
            },
        ),
    ]
