# Generated by Django 2.2.17 on 2021-06-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_data', '0023_enterpriselearner_enterpriselearnerenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriselearner',
            name='enterprise_user_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enterpriselearnerenrollment',
            name='course_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='enterpriselearnerenrollment',
            name='course_start_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriselearnerenrollment',
            name='enrollment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='enterpriselearnerenrollment',
            name='is_consent_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enterpriselearnerenrollment',
            name='passed_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='enterpriselearnerenrollment',
            name='unenrollment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='enterpriselearnerenrollment',
            name='unenrollment_end_within_date',
            field=models.DateField(null=True),
        ),
    ]
