# Generated by Django 3.2.13 on 2022-08-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_data', '0029_enterpriseoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriselearnerenrollment',
            name='primary_key',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
