# Generated by Django 3.2.14 on 2022-07-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_data', '0029_enterpriseoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriselearnerenrollment',
            name='completion_percentage',
            field=models.FloatField(null=True),
        ),
    ]
