# Generated by Django 3.2.13 on 2022-08-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_data', '0030_enterpriselearnerenrollment_add_primary_key_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriselearnerenrollment',
            name='enterprise_enrollment_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='enterpriselearnerenrollment',
            name='primary_key',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
