# Generated by Django 3.2.13 on 2022-08-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_data', '0032_enterpriselearnerenrollment_nullable_enterprise_enrollment_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enterpriselearnerenrollment',
            table='enterprise_learner_enrollment_2',
        ),
    ]
