# Generated by Django 3.2.20 on 2023-09-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_data', '0034_enterprisesubsidybudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriselearnerenrollment',
            name='budget_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
    ]
