# Generated by Django 3.2.20 on 2023-10-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_data', '0037_alter_enterpriseenrollment_consent_granted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseadminsummarizeinsights',
            name='contract_end_date',
            field=models.DateTimeField(help_text='Contract end date', null=True),
        ),
    ]
