# Generated by Django 3.2.23 on 2024-07-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_data', '0040_auto_20240718_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriselearnerenrollment',
            name='enterprise_enrollment_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='enterpriselearnerenrollment',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
