# Generated by Django 3.2.23 on 2024-07-18 05:48

from django.db import migrations, models

import enterprise_data.utils


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_data', '0041_auto_20240718_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriselearnerenrollment',
            name='id',
        ),
        migrations.AlterField(
            model_name='enterpriselearnerenrollment',
            name='lpr_unique_id',
            field=models.PositiveBigIntegerField(default=enterprise_data.utils.get_unique_id, primary_key=True, serialize=False),
        ),
    ]
