# Generated by Django 4.2.16 on 2024-12-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_data', '0044_enterpriseexecedlcmoduleperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseGroupMembership',
            fields=[
                ('is_applies_to_all_contexts', models.BooleanField(default=False)),
                ('enterprise_customer_id', models.UUIDField()),
                ('enterprise_group_name', models.CharField(max_length=255, null=True)),
                ('enterprise_group_uuid', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('group_is_removed', models.BooleanField(default=False)),
                ('group_type', models.CharField(max_length=128, null=True)),
                ('activated_at', models.DateTimeField(null=True)),
                ('enterprise_customer_user_id', models.PositiveIntegerField(null=True)),
                ('membership_is_removed', models.BooleanField(default=False)),
                ('membership_status', models.CharField(max_length=128, null=True)),
                ('enterprise_group_membership_uuid', models.UUIDField(null=True)),
            ],
            options={
                'verbose_name': 'Group Membership',
                'verbose_name_plural': 'Group Memberships',
                'db_table': 'group_membership',
            },
        ),
        migrations.AlterModelOptions(
            name='enterpriseexecedlcmoduleperformance',
            options={'verbose_name': 'Exec Ed LC Module Performance', 'verbose_name_plural': 'Exec Ed LC Module Performance'},
        ),
    ]
