"""
Module containing queries for the fact_enrollment_admin_dash table.
"""

from .fact_engagement_admin_dash import FactEngagementAdminDashQueries as FactEngagementAdminDashQueries
from .fact_enrollment_admin_dash import FactEnrollmentAdminDashQueries as FactEnrollmentAdminDashQueries
from .skills_daily_rollup_admin_dash import SkillsDailyRollupAdminDashQueries as SkillsDailyRollupAdminDashQueries
